/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "Achievement Gotten!": "成就达成!",
    "On": "打开",
    "Off": "关闭",
    "Your tree is": "你的树龄是",
    "Cost:": "成本:",
    "Never": "从不",
    "old.": "。",
    "Tree age": "树龄",
    "WIPE!!!": "擦除!!!",
    "Addition": "增幅加成",
    "Advanced": "高阶模式",
    "Advanced Purchased Upgrades Visibility": "已购高级升级显示",
    "Currency Pins": "货币置顶",
    "Exponent": "指数倍率",
    "Export as file": "导出文件",
    "Hide upgrades when:": "隐藏升级条件",
    "Import from file": "文件导入",
    "Import from prompt": "文本导入",
    "Inspired by": "灵感源自",
    "Instantly": "即刻生效",
    "Layers": "层",
    "Leaf Upgrades": "树叶升级",
    "Leaves": "树叶",
    "Leaves.": "树叶。",
    "Main Settings": "通用设置",
    "Multiplier": "倍率系数",
    "Scientific Notation starts at:": "科学计数起始值",
    "Start generating Leaves and Tree Age.": "开始生成树叶与树龄",
    "Static Exponent": "固定指数",
    "Static Multiplier": "固定倍率",
    "The Really Upgrade Tree of Life - Made by": "真实升级生命树 — 制作者",
    "The Upgrade Tree of Life": "生命之树升级体系",
    "Upgrades bought (faster)": "已购升级优先（较快）",
    "Upgrades bought or don't meet purchased upgrades (fastest)": "已购/未达成条件升级优先（极速）",
    "to Leaves.": "到叶子.",
    "Effect:": "效果:",
    "Tree Age boosts Leaves more.": "树龄越大，叶子数量就越多。",
    "Tree Age boosts Leaves.": "树龄提升树叶。",
    "Reach": "达到",
    "Seeds.": "种子.",
    "Leaves are increased by": "树叶生产提高",
    "compounding every purchased upgrade.": "每次购买的升级都进行累加。",
    "Leaves boost themselves.": "树叶提升自身。",
    "Seed Upgrades": "种子升级",
    "Tree Age boosts Leaves even more.": "树龄提升树叶更多。",
    "Decompolize your tree for": "分解你的树以获得",
    "Seeds": "种子",
    "Seeds boost Leaves generation.": "种子提升树叶生成。",
    "Seeds boost themselves.": "种子提升自身。",
    "Base": "基础",
    "Unlock more Leaf upgrades permanently.": "永久解锁更多树叶升级。",
    "'s effect is": "的效果是",
    "Fruits.": "水果。",
    "to Seeds.": "到种子。",
    "to Leaves and Seeds.": "到树叶和种子。",
    "squared": "平方的",
    "Leaves boost themselves more.": "树叶提升自身更多。",
    "Leaves boost Seeds gain.": "树叶提升种子增益。",
    "Fruits": "水果",
    "Fruit Upgrades": "水果升级",
    "Harvest your tree for": "收获你的树以获得",
    "Composter": "堆肥器",
    "Unlock the Composter.": "解锁堆肥器。",
    "Unlock the second Composter.": "解锁第二个堆肥器。",
    "(ETA:": "预计耗时：",
    "Compost": "堆肥",
    "Composting Speed": "堆肥速度",
    "Fertilizers": "肥料",
    "fertilizers using this composter.": "可使用此堆肥器制作肥料",
    "multiplier on Tree aging speed. (Base:": "树木生长老化速度乘数（基础值：",
    "The Leaf Composter": "树叶堆肥器",
    "Time required:": "所需时长：",
    "total fertilizers, translated to a": "全部肥料，可转化为",
    "You have made": "你已制作",
    "to Fruits.": "到水果。",
    "'s compounding effect is increased to": "的叠加效应提高到",
    "Leaves boost Composting speed.": "树叶提升堆肥的速度。",
    "to Composting speed.": "到堆肥速度。",
    "Leaves give a boost to Tree aging speed.": "树叶会加快树木的老化速度。",
    "Unlock the third Composter.": "解锁第三个堆肥器。",
    "The Seed Composter": "种子堆肥器",
    "Tree aging speed": "树木老化速度",
    "'s effect softcap is weaker.": "的效果软上限变弱。",
    "to Leaves,": "到树叶,",
    "to Seeds,": "到种子,",
    "compounding per total fertilizer.": "复合每总肥料。",
    "The Fruit Composter": "水果堆肥器",
    "Seeds are increased by": "种子提升了",
    "to Tree aging speed.": "到树木老化速度。",
    "'s effect's exponent is increased by Fruits.": "的效果指数随水果的增加而增加。",
    "Leaves boost Fruits gain.": "树叶提升水果增益。",
    "to Leaves, Seeds, Fruits.": "到树叶, 种子, 水果.",
    "scaled fertilizers using this composter.": "使用这种堆肥器缩放肥料。",
    "Unlock a new Leaf upgrade permanently.": "永久解锁一个新的树叶升级。",
    "leaf root in the PE formula.": "树叶根在潜在能量公式中。",
    "seed root in the PE formula.": "种子根在潜在能量公式中。",
    "Potential Energy": "潜在能量",
    "to Fruits. It causes": "到水果。它会导致",
    "Entropy Upgrades": "熵升级",
    "Entropy.": "熵。",
    "to static Seed multiplier.": "到静态种子乘数。",
    "Potential Energy.": "潜在能量。",
    "Entropy": "熵",
    "Transform your tree into some powerful energy for": "把你的树转化成一些强大的能量",
    "Cellular Lab": "细胞实验室",
    "Fruits boost themselves.": "水果提升自身。",
    "Keep": "保留",
    "on Harvest and Transform.": "收获与转化时。",
    "permanently.": "永久生效。",
    "Require:": "解锁条件：",
    "Start with the first 3 Composters unlocked on Transform.": "转化玩法初始解锁前三个堆肥器",
    "to static Leaf multiplier.": "为静态树叶乘数。",
    "Unlock the": "解锁",
    "(next at": "(下一个在",
    "[Enabled]": "[已启用]",
    "[Disabled]": "[已禁用]",
    "Automate first-purchased Fruit upgrades.": "自动购置首批果实强化",
    "Automate first-purchased Leaf upgrades.": "自动购置首批树叶强化",
    "Automate first-purchased Seed upgrades.": "自动购置首批种子强化",
    "Automation": "自动化",
    "Bacteria Type": "细菌种类",
    "Bacteria Types.": "细菌种类。",
    "Cells": "细胞",
    "Cells) Cellular Setup.": "细胞) 细胞设置。",
    "Decrease replicate interval.": "缩短复刻间隔",
    "Extend Limit, but unlock": "扩充上限，同时解锁",
    "Fruit Upgrades Automation": "果实强化自动启用",
    "Increase replicate chance.": "提升复刻概率",
    "Leaf Upgrades Automation": "树叶强化自动启用",
    "Level": "等级",
    "multiplier to Fruits.": "乘数到水果。",
    "multiplier to Leaves,": "乘数到树叶，",
    "multiplier to Seeds,": "乘数到种子，",
    "Seed Upgrades Automation": "种子升级自动化",
    "to Bacteria": "到细菌",
    "to Cell Limit,": "到细胞上限，",
    "Fertilizers boost Composting speed at a reduced rate.": "肥料能加快堆肥的速度，但效果会有所减弱。",
    "(softcapped)": "(软上限)",
    "Ash": "灰烬",
    "Ash Upgrades": "灰烬强化",
    "Bacteria": "细菌",
    "Beneficial Virus": "有益病毒",
    "Challenges": "挑战",
    "Fallen Leaf Upgrades": "落叶升级",
    "Fallen Leaves": "落叶",
    "Heat": "热能",
    "Root Upgrades": "根系强化",
    "Roots": "根系",
    "Sacred Leaves": "神圣树叶",
    "The Statue": "远古神像",
    "The Tree": "生命巨树",
    "Virus": "病毒",
    "Ash.": "灰烬",
    "Fallen Leaves.": "落叶。",
    "Reinforce your tree and go underground for": "稳固巨根系基，深入地底获取",
    "Respec Root Upgrades": "重置根系强化点数",
    "Roots.": "根系",
    "superscaled fertilizers using this composter.": "此堆肥装置可产出超规格肥料",
    "The Entropy Composter": "熵能堆肥器",
    "These fertilizers increase the fertilizer's base by": "此类肥料可提升肥料基础数值",
    "total Roots.": "总计根系。",
    "Virus Multiplier": "病毒乘数",
    ", and": ", 和",
    "' cost.": "' 成本.",
    "(ratio": "(率",
    "and": "和",
    "and are": "和",
    "| Basket cap:": "| 篮子上限:",
    "Bronze Leaves": "青铜树叶",
    "Golden Leaves": "黄金树叶",
    "Diamond Leaves": "钻石树叶",
    "to": "到",
    "Reward:": "奖励:",
    "Sacred Leaves.": "神圣树叶。",
    "Auto-Composting": "自动堆肥",
    "Best score:": "最高纪录：",
    "Burning Days": "焚烬时日",
    "Decrease Bronze Leaves conversion.": "降低青铜树叶转化效率",
    "Decrease Diamond Leaves conversion.": "降低钻石树叶转化效率",
    "Decrease Fallen Leaves conversion.": "降低落叶转化效率",
    "Decrease Golden Leaves conversion.": "降低黄金树叶转化效率",
    "Decrease Platinum Leaves conversion.": "降低白金树叶转化效率",
    "Decrease Silver Leaves conversion.": "降低白银树叶转化效率",
    "Drought": "大旱时节",
    "Entropy boosts": "熵能增幅",
    "Fall": "暮秋时节",
    "Fertilizers don't give a boost. You cannot gain Cells and Bacteria. Entropy is rooted by": "肥料不再提供增益，无法获取细胞与菌群，熵能数值固定不变",
    "Fruits gain is always": "果实收益永久固定",
    "Incinerator": "焚化炉",
    "Increase Ash gain.": "提升灰烬获取量",
    "Increase Basket cap.": "提升收纳篮容量",
    "Increase Bronze Leaves gain.": "提升青铜树叶产出",
    "Increase Diamond Leaves gain.": "提升钻石树叶产出",
    "Increase Fallen Leaves gain.": "提升落叶产出",
    "Increase Fallen Leaves of all types.": "提升全品类落叶产出",
    "Increase Golden Leaves gain.": "提升黄金树叶产出",
    "Increase Heat gain.": "提升热能获取量",
    "Increase Incinerator's Entropy buff.": "强化焚化炉熵能加成",
    "Increase Leaves and Seeds gain.": "提升树叶与种子产出",
    "Increase Leaves falling speed and Basket cap.": "提升树叶飘落速度并扩充收纳篮上限",
    "Increase Leaves falling speed.": "提升树叶飘落速度",
    "Increase Platinum Leaves gain.": "提升白金树叶产出",
    "Increase Roots gain.": "提升根系产出",
    "Increase Sacred Leaves gain.": "提升圣耀树叶产出",
    "Increase Silver Leaves gain.": "提升白银树叶产出",
    "Leaves and Tree aging speed are rooted by": "树叶产出与树木老化速度数值固定不变",
    "Leaves falling speed:": "树叶飘落速度：",
    "New exponentially increasing": "全新指数递增机制",
    "of your pending Fruits permanently, and unlock": "永久留存部分待收获果实，同时解锁",
    "of your pending Sacred Leaves permanently.": "永久留存部分待收获圣耀树叶",
    "of your pending Seeds permanently, and Entropy boosts": "永久留存部分待收获种子，解锁熵能增幅效果",
    "Passively generate": "被动持续产出",
    "permanently, and Bacteria boosts Leaves by": "永久生效，菌群增幅树叶产出效率",
    "Platinum Leaves": "白金树叶",
    "Raise static Leaf miltiplier.": "提升固定树叶倍率",
    "Raise Virus gain.": "提升病毒产出量",
    "Repeatable Entropy Upgrades": "可重复熵能强化",
    "Repeatable Fruit Upgrades": "可重复果实强化",
    "Repeatable Leaf Upgrades": "可重复树叶强化",
    "Repeatable Root Upgrades": "可重复根系强化",
    "Repeatable Seed Upgrades": "可重复种子强化",
    "repeatable upgrades' level cap, except itself.": "提升其余所有可重复强化等级上限（自身除外）",
    "Sacrifice your Fallen Leaves for": "献祭落叶换取",
    "Season is challenge that forces a reinforcement and gives debuffs upon entering. To beat a season, you need to pass the requirement below.": "时令挑战开启后强制进行根基加固，同时附带负面效果，达成指定条件即可通关该时令挑战",
    "Silver Leaves": "白银树叶",
    "Snowfall": "落雪时节",
    "Spring": "生机春日",
    "square-rooted": "平方根缩放",
    "stat has been added. Weathers' reward is weaker. Incinerators are useless. Entropy is": "新增属性词条，气象挑战奖励削弱，焚化炉失效，熵能效果",
    "Static Leaf, Tree aging speed, Seed, and Fruit multipliers are powered by": "固定树叶、树龄、种子、果实倍率由其驱动",
    "Storm": "狂风暴雨",
    "stronger, and bonus Fertilizers are disabled. Entropy Fertilizers don't count the score.": "效果增强，额外肥料失效，熵能肥料不计入评分",
    "Summer": "炽烈盛夏",
    "Superscaled Fertilizers always start at": "超阶肥料初始固定数值",
    "The exponent of Leaves, Seeds, and Fruits is reduced by": "树叶、种子、果实指数倍率降低",
    "The Season": "时令篇章",
    "The Weather": "气象异变",
    "These are repeatable upgrades! But they have level cap, so it can be increased by late upgrades. The new repeatable upgrade is unlocked by reaching 100 levels of the previous upgrade.": "此类为可循环强化，存在等级上限，可通过后期强化提升上限；解锁下一循环强化需将前一项强化升至100级",
    "to Bacteria's limit.": "提升菌群容量上限",
    "to Cell replication speed.": "提升细胞复刻速度",
    "to Entropy.": "提升熵能数值",
    "to Fallen Leaves.": "提升落叶产出",
    "to Leaves and Tree aging speed.": "提升树叶产出与树木老化速度",
    "to Leaves, Seeds, and Fruits.": "提升树叶、种子、果实整体收益",
    "to Potential Energy.": "提升势能数值",
    "to Seeds and Fruits.": "提升种子与果实收益",
    "to the first 3 Fertilizers' cost.": "降低前三类肥料基础消耗",
    "Tree age boosts": "树龄属性增幅",
    "True Autumn Leaves": "纯正秋叶",
    "Weather Intensity": "气象强度",
    "Weather is challenge that forces a transformation and gives debuffs upon entering. To beat a weather, you need to pass the requirement below.": "气象挑战开启后强制触发形态异变并附加负面效果，达成指定条件即可通关",
    "While in challenge, the Cell's effects are reduced by": "挑战期间，细胞各项效果削减",
    "(in": "(在",
    "Add": "增加",
    "'s cost.": "的成本。",
    "'s effect": "的效果",
    "'s effect.": "的效果。",
    "'s base.": "的基数。",
    "' base.": "' 基数。",
    "'s level.": "的等级。",
    "'s level cap.": "的等级上限。",
    "boost Entropy.": "提升熵。",
    "boost Seeds.": "提升种子。",
    "boost Leaves.": "提升树叶。",
    "boost Fruits.": "提升水果。",
    "Add bonus Fertilizers of all types.": "添加全类型额外肥料",
    "affects": "影响",
    "applies to the fourth Composter.": "适用于第四个堆肥器",
    "Are you kidding me?": "你在逗我？",
    "Ash boosts Heat.": "灰烬提升热能",
    "Ash divides Coal requirement.": "灰烬降低煤炭需求",
    "Ash,": "灰烬，",
    "Ash)": "灰烬)",
    "Auto-Bacteria Upgrades": "细菌升级自动启用",
    "Auto-Brozen Leaf Upgrades": "青铜树叶升级自动启用",
    "Auto-Cell Upgrades": "细胞升级自动启用",
    "Auto-Entropy Upgrades": "熵升级自动启用",
    "Auto-Fallen Leaf Upgrades": "落叶升级自动启用",
    "Auto-Golden Leaf Upgrades": "黄金树叶升级自动启用",
    "Auto-Platinum Leaf Upgrades": "白金树叶升级自动启用",
    "Auto-Silver Leaf Upgrades": "白银树叶升级自动启用",
    "Automate Bacteria upgrades.": "自动购置细菌升级",
    "Automate Bronze Leaf upgrades.": "自动购置青铜树叶升级",
    "Automate Cell upgrades.": "自动购置细胞升级",
    "Automate Fallen Leaf upgrades.": "自动购置落叶升级",
    "Automate first-purchased Entropy upgrades.": "自动购置首批熵强化",
    "Automate Golden Leaf upgrades.": "自动购置黄金树叶升级",
    "Automate Platinum Leaf upgrades.": "自动购置白金树叶升级",
    "Automate repeatable Entropy upgrades.": "自动购置可重复熵强化",
    "Automate repeatable Fruit upgrades.": "自动购置可重复果实强化",
    "Automate repeatable Leaf upgrades.": "自动购置可重复树叶强化",
    "Automate repeatable Seed upgrades.": "自动购置可重复种子强化",
    "Automate Silver Leaf upgrades.": "自动购置白银树叶升级",
    "Automatically compost Leaves, Seeds, Fruits, and Entropy without taking them away.": "自动堆肥树叶、种子、果实和熵而不消耗它们",
    "Bacteria limit is increased by Entropy linearly.": "细菌上限随熵线性增加",
    "Bacteria slightly boosts Cell replication speed.": "细菌略微提升细胞复刻速度",
    "Bacteria Type on Reinforcement.": "加固时的细菌种类",
    "Bacteria Types also increase Bacteria's limit.": "细菌种类同时提升细菌上限",
    "Bacteria Upgrades Automation": "细菌升级自动化",
    "bonus Leaf Fertilizers per": "每额外树叶肥料",
    "bonus of first 3 Fertilizers per": "每前三类肥料额外",
    "bonus Seed Fertilizers per": "每额外种子肥料",
    "Bronze Leaf Upgrades Automation": "青铜树叶升级自动化",
    "Cell replication decrease is weaker.": "细胞复刻速度下降效果减弱",
    "Cell slightly boosts Entropy.": "细胞略微提升熵",
    "Cell Upgrades Automation": "细胞升级自动化",
    "Cells and": "细胞和",
    "Cells boost Tree aging speed.": "细胞提升树木老化速度",
    "Cells can now exceed their limit, so Bacteria Types are automatically gained.": "细胞现在可以超过上限，因此自动获得细菌种类",
    "Cells weaken Bacteria's limit slowdown.": "细胞削弱细菌上限减速效果",
    "Charcoal": "木炭",
    "Coal": "煤炭",
    "Coal doesn't reset on Reinforcement.": "煤炭在加固时不会重置",
    "Coal's Root effect is": "煤炭的根系效果是",
    "Composting Automation": "自动堆肥",
    "Composting speed divides the first 3 Fertilizers' cost.": "堆肥速度降低前三类肥料成本",
    "Composting speed.": "堆肥速度",
    "compounding per Charcoal.": "每木炭叠加",
    "Convert all your Cells and Entropy for": "将所有细胞和熵转化为",
    "Delay Sueprscaled Fertilizers.": "延迟超阶肥料",
    "divide": "降低",
    "Divide": "降低",
    "divides Entropy Fertilizer's cost.": "降低熵肥料成本",
    "divides itself.": "降低自身",
    "Entropy boosts Beneficial Virus permanently.": "熵永久提升有益病毒",
    "Entropy boosts itself logarithmically.": "熵以对数方式提升自身",
    "Entropy boosts Roots.": "熵提升根系",
    "Entropy boosts static Fruit multiplier.": "熵提升静态果实倍率",
    "Entropy divides Coal requirement.": "熵降低煤炭需求",
    "Entropy Fertilizers.": "熵肥料",
    "Entropy increases the exponent of Roots gain formula.": "熵增加根系获取公式的指数",
    "Entropy Upgrades Automation": "熵升级自动化",
    "exponent to Leaves, Seeds, and Fruits.": "树叶、种子、果实的指数",
    "Fall challenge's best score boosts Fallen Leaves.": "秋季挑战最高分提升落叶",
    "Fallen Leaf Upgrades Automation": "落叶升级自动化",
    "Fallen Leaves are increased by": "落叶提升了",
    "fertilizer's base,": "肥料基础，",
    "FR1": "FR1",
    "FR2": "FR2",
    "Fruit Fertilizers, starting at": "果实肥料，起始为",
    "Fruits are increased by": "果实提升了",
    "Fruits boost Leaves at a reduced rate.": "果实以降低的速率提升树叶",
    "Fruits boost Seeds gain.": "果实提升种子增益",
    "Fruits boost static Seed multiplier.": "果实提升静态种子倍率",
    "Fruits divide": "果实降低",
    "Golden Leaf Upgrades Automation": "黄金树叶升级自动化",
    "Heat & Ash": "热能与灰烬",
    "I don't care about that Infinistal's warning about static multiplier.": "我才不在乎Infinistal关于静态倍率的警告",
    "Improve": "提升",
    "Improve Cell's effects.": "提升细胞效果",
    "Improve Sacred Leaves gain.": "提升圣耀树叶产出",
    "Incinerator Level:": "焚化炉等级：",
    "Incinerator's debuffs are weaker.": "焚化炉的负面效果减弱",
    "Incinerator's maximum input is increased by total Roots.": "焚化炉最大输入随总根系增加",
    "Incinerator's maximum input:": "焚化炉最大输入：",
    "Increase Beneficial Virus gain.": "提升有益病毒产出",
    "Increase Entropy gain.": "提升熵产出",
    "Increase Incinerator's maximum input by": "提升焚化炉最大输入",
    "Increase Mutation chance.": "提升变异概率",
    "Increase replicate amount.": "提升复刻数量",
    "Increase Virus gain.": "提升病毒产出",
    "Infinity Leaves!": "无限树叶！",
    "is raised by Fruits.": "由果实提升",
    "Keep Cells on Transform.": "转化时保留细胞",
    "Leaves boost Leaves falling speed.": "树叶提升飘落速度",
    "Leaves increase the exponent of Roots gain formula.": "树叶增加根系获取公式指数",
    "Leaves:": "树叶：",
    "Max": "最大",
    "multiplier to Entropy.": "乘数到熵",
    "Mutation: (log": "变异：(对数",
    "of your Entropy on Bacteria.": "部分熵作用于细菌",
    "of your pending Bacteria permanently.": "永久保留部分待定细菌",
    "of your pending Entropy permanently.": "永久保留部分待定熵",
    "of your pending Roots permanently.": "永久保留部分待定根系",
    "per purchased upgrade, starting at": "每购买升级，起始于",
    "per total fertilizer, starting at": "每总肥料，起始于",
    "Platinum Leaf Upgrades Automation": "白金树叶升级自动化",
    "Prepare for the next layer.": "准备进入下一层",
    "Reload Reinforcement": "重载加固",
    "Repeatable Entropy Upgrades Automation": "可重复熵升级自动化",
    "Repeatable Fruit Upgrades Automation": "可重复果实升级自动化",
    "Repeatable Leaf Upgrades Automation": "可重复树叶升级自动化",
    "Repeatable Seed Upgrades Automation": "可重复种子升级自动化",
    "Replicate Bacteria faster again.": "再次加快细菌复刻",
    "Replicate Bacteria faster.": "加快细菌复刻",
    "Replicate interval is divided by Entropy.": "复刻间隔由熵降低",
    "RO17-20": "根系17-20",
    "RO24-26": "根系24-26",
    "RO31-34": "根系31-34",
    "RO4-7": "根系4-7",
    "Roots boost Virus.": "根系增强病毒",
    "Roots divide": "根系降低",
    "Sacred Leaf upgrades no longer take Sacred Leaves away permanently.": "神圣树叶升级不再永久移除圣耀树叶",
    "Sacred Leaves boost": "圣耀树叶增强",
    "scaled Fertilizer starting,": "缩放肥料起始，",
    "Scaled Fertilizers start later by Entropy.": "缩放肥料由熵延后开始",
    "season permanently.": "季节永久",
    "Seed Fertilizers, starting at": "种子肥料，起始于",
    "Seeds boost static Leaf multiplier.": "种子增强树叶静态倍率",
    "Silver Leaf Upgrades Automation": "白银树叶升级自动化",
    "static multiplier to Tree aging speed.": "树木老化速度的静态倍率",
    "Storm reward affects Fruits at a reduced rate.": "风暴奖励以降低速率影响水果",
    "Storm reward affects Seeds at a reduced rate.": "风暴奖励以降低速率影响种子",
    "stronger.": "更强",
    "Summer challenge's best score boosts Coal's 1st effect and Charcoal's effects.": "夏季挑战最高分增强煤炭首效果和木炭效果",
    "Superscaled Fertilizers are": "超阶肥料是",
    "Superscaled Fertilizers are delayed by": "超阶肥料由...延后",
    "Superscaled Fertilizers are delayed by total Roots.": "超阶肥料由总根系延后",
    "tab) permanently.": "标签页)永久",
    "The 1st Virus upgrade gain a bonus level per the 2nd and 3rd Virus upgrades.": "第一病毒升级获得二三级病毒升级的额外等级",
    "The 2nd Cell upgrade gain a bonus level per the 3rd Cell upgrade.": "第二细胞升级获得第三细胞升级的额外等级",
    "The first Cell upgrade is exponentially stronger.": "第一细胞升级呈指数增强",
    "the Furnace": "熔炉",
    "The Furnace": "熔炉",
    "the Incinerator": "焚化炉",
    "The Incinerator": "焚化炉",
    "The Leaf and Seed Composters no longer reset on Harvest.": "树叶和种子堆肥器在收获时不再重置",
    "times, translated to": "次，转化为",
    "to Ash.": "到灰烬",
    "to Bacteria.": "到细菌",
    "to Bactieria replication speed, and its limit is raised by total Roots.": "到细菌复制速度，且其上限由总根系提升",
    "to Basket cap.": "到收纳篮上限",
    "to Bronze Leaves.": "到青铜树叶",
    "to Charcoal requirement.": "到木炭需求",
    "to Composting speed,": "到堆肥速度，",
    "to cost of": "到...成本",
    "to Entropy. Start with": "到熵。以...开始",
    "to Fallen Leaves of all types.": "到全类型落叶",
    "to Fruits and Tree aging speed.": "到水果和树木老化速度",
    "to Fruits,": "到水果，",
    "to Golden Leaves.": "到黄金树叶",
    "to Heat and Ash.": "到热能和灰烬",
    "to Heat.": "到热能",
    "to L,S,F and": "到L,S,F和",
    "to Leaves and Fruits,": "到树叶和水果，",
    "to Leaves and Fruits.": "到树叶和水果",
    "to Leaves and Tree aging speed,": "到树叶和树木老化速度，",
    "to Leaves falling speed and Basket cap.": "到树叶飘落速度和收纳篮上限",
    "to Leaves falling speed.": "到树叶飘落速度",
    "to Leaves, Seeds, Fruits, and Cell replication speed.": "到树叶、种子、水果和细胞复制速度",
    "to Leaves, Seeds, Fruits, and Entropy.": "到树叶、种子、水果和熵",
    "to Leaves, Seeds, Fruits, and Tree aging speed,": "到树叶、种子、水果和树木老化速度，",
    "to Leaves, Seeds, Fruits, and Tree aging speed.": "到树叶、种子、水果和树木老化速度",
    "to Leaves, Seeds, Fruits, Tree aging speed, and Cell replication speed.": "到树叶、种子、水果、树木老化速度和细胞复制速度",
    "to Leaves, Tree aging speed, and Seeds and": "到树叶、树木老化速度和种子及",
    "to Platinum Leaves.": "到白金树叶",
    "to Roots.": "到根系",
    "to Sacred Leaves and Roots,": "到圣耀树叶和根系，",
    "to Sacred Leaves.": "到圣耀树叶",
    "to Silver Leaves.": "到白银树叶",
    "to static Entropy multiplier.": "到静态熵倍率",
    "to static Fruit multiplier.": "到静态水果倍率",
    "to static TAS multiplier.": "到静态TAS倍率",
    "to Tree aging speed and Cell replication speed.": "到树木老化速度和细胞复制速度",
    "to True Autumn Leaves.": "到纯正秋叶",
    "to Virus permanently.": "到病毒永久",
    "to Virus.": "到病毒",
    "Total Roots": "总根系",
    "Total Roots boost Ash.": "总根系增强灰烬",
    "Total Roots boost the first Bacteria effect at an extremely reduced rate.": "总根系以极低速率增强首个细菌效果",
    "Total Roots increase Basket cap.": "总根系增加收纳篮上限",
    "total Roots)": "总根系)",
    "Transform gives twice as much entropy.": "转化提供双倍熵",
    "Tree age boosts Entropy.": "树龄增强熵",
    "Tree age boosts Fruits.": "树龄增强水果",
    "Tree Age boosts itself.": "树龄增强自身",
    "Tree age boosts Seeds.": "树龄增强种子",
    "Tree age slowdown is": "树龄减速是",
    "True Autumn Leaves boost Sacred Leaves.": "纯正秋叶增强圣耀树叶",
    "twice": "双倍",
    "Unlock a new repeatable Entropy upgrade permanently.": "永久解锁新的可重复熵升级",
    "Unlock a new repeatable Fruit upgrade permanently.": "永久解锁新的可重复果实升级",
    "Unlock a new repeatable Root upgrade permanently.": "永久解锁新的可重复根系升级",
    "Unlock a new repeatable Seed upgrade permanently.": "永久解锁新的可重复种子升级",
    "Unlock a new set of Challenges permanently.": "永久解锁新的挑战合集",
    "Unlock a new upgrade in cells tab.": "在细胞标签页解锁新升级",
    "Unlock new Leaf upgrades permanently.": "永久解锁新的树叶升级",
    "Unlock the fourth Composter.": "解锁第四个堆肥器",
    "Unlock the third Bacteria upgrade.": "解锁第三个细菌升级",
    "Virus | Bacteria:": "病毒 | 细菌：",
    "Virus is reset on Transform. You can't gain Virus outside Spring.": "病毒在转化时重置，春季外无法获得病毒",
    "Wait, that's illegal.": "等等，这不合规",
    "weaker again.": "再次减弱",
    "weaker.": "减弱",
    "Weather Forecast building": "天气预报建筑",
    "Weather goals no longer reset on Reinforcement.": "天气目标在加固时不再重置",
    "Welcome back!": "欢迎回来！",
    "with a new repeatable upgrade permanently.": "永久获得新的可重复升级",
    "You can incinerate Leaves.": "可以焚化树叶",
    "You can incinerate Seeds.": "可以焚化种子",
    "You can produce as much fertilizer as resources allow and as composting speed increases.": "可根据资源允许和堆肥速度提升尽可能多地生产肥料",
    "You have incinerated": "已焚化",
    ", and its level cap is increased by Entropy.": "，其等级上限由熵提升。",
    ", and its level cap is increased by total Roots.": "，其等级上限由总根系提升。",
    "' cost scaling by": "'成本缩放由...降低",
    "' level cap is increased by": "'等级上限由...提升",
    "' level cap is increased by Fallen Leaves.": "'等级上限由落叶提升。",
    "' level cap is increased by Leaves falling speed.": "'等级上限由树叶飘落速度提升。",
    "'s base is increased by": "'的基数由...提升",
    "'s base is increased by Ash.": "'的基数由灰烬提升。",
    "'s base is increased by Entropy.": "'的基数由熵提升。",
    "'s base is increased by total Roots.": "'的基数由总根系提升。",
    "'s compounding effect is affected by": "'的叠加效果受...影响",
    "'s compounding effect is increased by": "'的叠加效果由...提升",
    "'s compounding effect is increased by Fruits.": "'的叠加效果由水果提升。",
    "'s cost scaling is weaker.": "'的成本缩放效果减弱。",
    "'s cost scaling.": "'的成本缩放。",
    "'s effect's exponent is increased by Entropy.": "'的效果指数由熵提升。",
    "'s effect's exponent is increased by Leaves.": "'的效果指数由树叶提升。",
    "'s effect's exponent is increased by Seeds.": "'的效果指数由种子提升。",
    "'s initial cost is lowered to": "'的初始成本降低至",
    "'s level boosts Bacteria's limit at a reduced rate.": "'的等级以降低的速率提升细菌上限。",
    "'s level cap is increased by": "'的等级上限由...提升",
    "'s level cap is increased by Bacteria.": "'的等级上限由细菌提升。",
    "'s level cap is increased by Fallen Leaves.": "'的等级上限由落叶提升。",
    "'s level cap is increased by total Roots.": "'的等级上限由总根系提升。",
    "Base Leaf's Fertilizer scaling is divided by": "基础树叶肥料缩放由...降低",
    "Base Seed's Fertilizer scaling is divided by": "基础种子肥料缩放由...降低",
    "boosts Tree aging speed.": "提升树木老化速度。",
    "(Next at": "(下一个在",
    "The": "这",
    "by": "由",
    "LSFER": "LSFER",
    "Mythic": "神话",
    "Legendary": "传说",
    "Epic": "史诗",
    "Rare": "稀有",
    "Uncommon": "罕见",
    "Common": "普通",
    "SPD": "速度",
    "ATK": "攻击",
    "ARM": "护甲",
    "Lvl": "等级",
    "Unlock": "解锁",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "MrRedShark77": "MrRedShark77",
    "(Roblox)": "(Roblox)",
    "1e303 (1Ce)": "1e303 (1Ce)",
    "1e33 (1Dc)": "1e33 (1Dc)",
    "= (log": "= (log",
    "× (log": "× (log",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "➜": "➜",
    "= (": "= (",
    "—": "—",
    "•": "•",
    "−": "−",
    "×": "×",
    "←": "←",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Cost: ": "成本: ",
    "Next at ": "下一个在 ",
    "Show Milestone Popups: ": "显示里程碑弹窗：",
    "Made by ": "作者 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/s)": "/秒)",
    "/s) Cells, translated to:": "/秒) 细胞, 转化为:",
    "/s) Virus, nerfed to:": "/秒) 病毒, 削弱为:",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^\^\-([\d\.]+)$/,
    /^\+\^([\d\.]+)$/,
    /^\(([\d\.]+)$/,
    /^\/([\d\.]+)$/,
    /^\(×([\d\.]+)$/,
    /^\(\+([\d\.]+)s$/,
    /^([\d\.]+)ms$/,
    /^× ([\d\.]+)\)$/,
    /^× ([\d\.]+)$/,
    /^: ([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)(.+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^\= ([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^: ([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\^([\d\.,]+)$/,
    /^\+([\d\.,]+)\%$/,
    /^\(\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^\(([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^\+ ([\d\.,]+)$/,
    /^× ([\d\.,]+)\)$/,
    /^\= ([\d\.,]+)$/,
    /^\/ ([\d\.]+)(.+)\)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^×e([\d\.]+)e([\d\.,]+)$/,
    /^\(×e([\d\.]+)e([\d\.,]+)$/,
    /^\^([\d\.]+) \(×([\d\.]+)e([\d\.,]+)\)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^It took you (.+) to beat the game.$/, '你通关游戏用了 $1。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^e([\d\.]+)e([\d\.,]+) Virus$/, 'e$1e$2 病毒'],
    [/^([\d\.]+) years$/, '$1 年'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^Composting \(([\d\.]+)\%\)$/, '堆肥中 ($1%)'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+) Leaves$/, '$1 叶子'],
    [/^([\d\.,]+) Fruits$/, '$1 水果'],
    [/^([\d\.,]+) yeas$/, '$1 年'],
    [/^([\d\.,]+) Seeds$/, '$1 种子'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) CS$/, '$1 细胞设置'],
    [/^([\d\.,]+) Entropy$/, '$1 熵'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^\[L([\d\.,]+)\]$/, '[树叶 $1]'],
    [/^\[S([\d\.,]+)\]$/, '[种子 $1]'],
    [/^\[F([\d\.,]+)\]$/, '[水果 $1]'],
    [/^\[E([\d\.,]+)\]$/, '[熵 $1]'],
    [/^\[ER([\d\.,]+)\]$/, '[ER $1]'],
    [/^\[FR([\d\.,]+)\]$/, '[FR $1]'],
    [/^\[LR([\d\.,]+)\]$/, '[LR $1]'],
    [/^\[ROM([\d\.,]+)\]$/, '[LR $1]'],
    [/^\[FA([\d\.,]+)\]$/, '[FA $1]'],
    [/^\[SR([\d\.,]+)\]$/, '[SR $1]'],
    [/^\[A([\d\.,]+)\]$/, '[A $1]'],
    [/^\[RO([\d\.,]+)\]$/, '[RO $1]'],
    [/^\[L\-([\d\.,]+)\]$/, '[L-$1]'],
    [/^\[ROR([\d\.,]+)\]$/, '[ROR $1]'],
    [/^L([\d\.,]+)$/, '树叶 $1'],
    [/^F([\d\.,]+)$/, '水果 $1'],
    [/^S([\d\.,]+)$/, '种子 $1'],
    [/^E([\d\.,]+)$/, '熵 $1'],
    [/^ROM([\d\.,]+)$/, 'ROM $1'],
    [/^RO([\d\.,]+)$/, 'RO $1'],
    [/^ROR([\d\.,]+)$/, 'ROR $1'],
    [/^LR([\d\.,]+)$/, 'LR $1'],
    [/^FA([\d\.,]+)$/, 'FA $1'],
    [/^ER([\d\.,]+)$/, 'ER $1'],
    [/^R([\d\.,]+)$/, 'R $1'],
    [/^SR([\d\.,]+)$/, 'SR $1'],
    [/^R([\d\.,]+)\-([\d\.,]+)$/, 'R $1-$2'],
    [/^LR([\d\.,]+)\-([\d\.,]+)$/, 'LR $1-$2'],
    [/^FR([\d\.,]+)\-([\d\.,]+)$/, 'FR $1-$2'],
    [/^Lvl ([\d\.,]+)$/, '等级 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Require: (.+) Roots$/, '需要：$1 根系'],
    [/^Require: (.+) Bacteria$/, '需要：$1 细菌'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
    [/^([\d\.]+)(.+) Leaves$/, '$1$2 树叶'],
    [/^([\d\.]+)(.+) Fruits$/, '$1$2 水果'],
    [/^([\d\.]+)(.+) Seeds$/, '$1$2 种子'],
    // 新增正则翻译
    [/^\(×([\d\.e+,]+)\/s\) Bacteria, translated to:$/, '(×$1/秒) 细菌, 转化为:'],
    [/^\(×e([\d\.e+,]+)\/s\) Virus, nerfed to (.+)$/, '(×e$1/秒) 病毒, 削弱至 $2)'],
    [/^\(floored\)\.$/, '(向下取整)。'],
    [/^\(Next at (.+)\)$/, '(下一个在 $1)'],
    [/^=0$/, '=0'],
    [/^\^(.+)$/, '^$1'],
    [/^\/([\d\.e+,]+) ➜$/, '/$1 ➜'],
    [/^e([\d\.]+),([\d\.]+) \/ e[\d\.]+,[\d\.]+$/, 'e$1,$2 / e$1,$2'],
    [/^e([\d\.]+)([\d\.]+) (.+)$/, 'e$1$2 $3'],

    [/^× ([\d\.]+)(.+)$/, '× $1$2)'],
    [/^\= ([\d\.]+)(.+)$/, '= $1$2)'],
    [/^×([\d\.]+)(.+)$/, '×$1$2)'],
    [/^\(([\d\.]+)(.+)$/, '($1$2'],
    [/^: ([\d\.]+) years$/, ': $1 年'],
    [/^: ([\d\.]+)(.+) years$/, ': $1$2 年'],
    [/^: ([\d\.]+)(.+)$/, ': $1$2'],
    [/^\(\+([\d\.]+)(.+) years$/, '(+$1$2 年'],
    [/^([\d\.]+) days (.+)$/, '$1 天 $2'],
    [/^\(\+([\d\.]+) days (.+)$/, '(+$1 天 $2'],
    [/^\(\+([\d\.]+)(.+)$/, '(+$1$2'],
    [/^([\d\.]+)(.+) Roots$/, '$1$2 根'],
    [/^([\d\.]+)(.+) Entropy$/, '$1$2 熵'],
    [/^([\d\.]+)(.+) years$/, '$1$2 年'],
    [/^([\d\.]+)(.+)$/, '$1$2'],

]);